name: Deploy Laravel Project

on:
  push:
    branches:
      - main  # Ganti dengan branch yang kamu inginkan

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl, zip  # Tambahkan extension lain jika perlu

      - name: Install Composer Dependencies
        run: |
          composer install --optimize-autoloader --no-dev

      - name: Optimize Laravel
        run: |
          php artisan optimize
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Deploy to Server
        run: |
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }} -e "mirror -R . <KEY_DIR>; bye"
