version: '1.0'

stages:
  - deploy

deploy:
  stage: deploy
  image: php:8.2-cli
  script:
    - apt-get update && apt-get install -y git zip unzip lftp
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - git clone <KEY_URL> .
    - composer install --optimize-autoloader --no-dev
    - php artisan optimize
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - lftp -u <KEY_USERNAME>,<KEY_PASSWORD> <KEY_SERVER> -e "mirror -R . <KEY_DIR>; bye"
